"""add_quality_score_to_reference

Revision ID: 4bf3a5f54be8
Revises: 736c812b73c2
Create Date: 2026-01-15 14:57:29.146826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf3a5f54be8'
down_revision = '736c812b73c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('references', sa.Column('quality_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('references', 'quality_score')
    # ### end Alembic commands ###