"""add_version_and_is_active_to_references

Revision ID: a1b2c3d4e5f6
Revises: 4bf3a5f54be8
Create Date: 2026-01-17 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '4bf3a5f54be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('references', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('references', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('references', 'is_active')
    op.drop_column('references', 'version')
    # ### end Alembic commands ###